services:
  - type: web
    name: logitrack-api
    runtime: docker
    rootDir: logitrack-api
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: logitrack-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,http://127.0.0.1:5173,https://logitrack-web.vercel.app,https://logitrack-e90yq8vzu-gabriels-projects-dde20f6b.vercel.app

databases:
  - name: logitrack-db
    databaseName: logitrack
    user: logitrack
    plan: free
    region: oregon
    postgresMajorVersion: "18"
